### PR TITLE
#166030713 make transitions faster, add responsive aside bars and make links active

### PR DESCRIPTION
**Pull request by successgilli**
#### What does this PR do?
It applies LFA feedback on my user and admin pages
#### Description of Task to be completed?
-user dashboard page is to have only one active loan
-all transitions are to be removed
-user and admin pages should have toggleable default sidebars on a laptop screen. 
-make all links active

#### How should this be manually tested?
Git clone the repo and cd into UI folder and open any of the user and admin pages on chrome.
#### What are the relevant pivotal tracker stories?
#166030713
#### Screenshots (if appropriate)

image

#### Questions:

### CODE REVIEW

**Comment by Oluwasegun-AA** [comment]
@successgilli centre the "Repayment history" heading and make sure the page is not scrolling horizontally

**Comment by Oluwasegun-AA** [comment]
@successgilli , also change the PR title to be a descriptive summary of what you're adding with the PR

**Comment by successgilli** [comment]
> 
I will center table titles and push.
The tables as a whole are already centered. I only made the mistake of taking a half picture of the UI.
I will change the name of the PR title

**Comment by Oluwasegun-AA** [comment]
@successgilli , Nice Job on the feedback implemented. Please remove all the descriptions in the Navbar, it defaces the view

**Comment by successgilli** [comment]
the navBar of my UI or my desktop screen? which one?

**Pull request merged**
